<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="UnityFactory\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Unity.RegistrationByConvention" Version="5.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LE.Billing.Service\LE.Billing.Service.csproj" />
  </ItemGroup>

</Project>
