<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LE.Billing.Common\LE.Billing.Common.csproj" />
    <ProjectReference Include="..\LE.Billing.Entities\LE.Billing.Entities.csproj" />
    <ProjectReference Include="..\LE.Common\LE.Common.csproj" />
    <ProjectReference Include="..\LE.Context\LE.Context.csproj" />
    <ProjectReference Include="..\LE.Inventory.Entities\LE.Inventory.Entities.csproj" />
  </ItemGroup>

</Project>
