// <auto-generated />
using System;
using LE.Context.Data;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LE.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914000000_p2_account_settings_unique_key")]
    partial class p2AccountSettingsUniqueKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("LE.Account.Entities.AccountSettings", b =>
                {
                    b.Property<long>("settings_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("value")
                        .HasColumnType("bigint");

                    b.HasKey("settings_id");

                    b.HasIndex("key")
                        .IsUnique();

                    b.ToTable("account_settings");
                });

            modelBuilder.Entity("LE.Account.Entities.FiscalYear", b =>
                {
                    b.Property<long>("fiscal_year_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("day")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("month")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("fiscal_year_id");

                    b.ToTable("fiscal_year");
                });

            modelBuilder.Entity("LE.Account.Entities.Ledger", b =>
                {
                    b.Property<long>("ledger_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_currently_used")
                        .HasColumnType("boolean");

                    b.Property<long>("ledger_group_id")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nep_created_date")
                        .HasColumnType("text");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("ledger_id");

                    b.HasIndex("ledger_group_id");

                    b.ToTable("ledger");
                });

            modelBuilder.Entity("LE.Account.Entities.LedgerBalance", b =>
                {
                    b.Property<long>("ledger_balance_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("balance")
                        .HasColumnType("numeric");

                    b.Property<long>("ledger_group_id")
                        .HasColumnType("bigint");

                    b.Property<long>("ledger_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ledger_balance_id");

                    b.HasIndex("ledger_group_id");

                    b.HasIndex("ledger_id");

                    b.ToTable("ledger_balance");
                });

            modelBuilder.Entity("LE.Account.Entities.LedgerGroup", b =>
                {
                    b.Property<long>("ledger_group_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_custom")
                        .HasColumnType("boolean");

                    b.Property<int>("ledger_group_type")
                        .HasColumnType("integer");

                    b.Property<long>("ledgers_count")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("parent_ledger_group_id")
                        .HasColumnType("bigint");

                    b.HasKey("ledger_group_id");

                    b.ToTable("ledger_group");
                });

            modelBuilder.Entity("LE.Account.Entities.LedgerSetup", b =>
                {
                    b.Property<long>("ledger_setup_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("key")
                        .IsRequired()
                        .HasColumnType("character varying(70)")
                        .HasMaxLength(70);

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.HasKey("ledger_setup_id");

                    b.ToTable("ledger_setup");
                });

            modelBuilder.Entity("LE.Account.Entities.Payment", b =>
                {
                    b.Property<long>("payment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric");

                    b.Property<long>("cancelled_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("cancelled_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("cheque_date")
                        .HasColumnType("text");

                    b.Property<string>("cheque_no")
                        .HasColumnType("text");

                    b.Property<decimal>("discount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_cancelled")
                        .HasColumnType("boolean");

                    b.Property<string>("nep_entry_date")
                        .HasColumnType("text");

                    b.Property<string>("nep_transaction_date")
                        .HasColumnType("text");

                    b.Property<long>("payment_from")
                        .HasColumnType("bigint");

                    b.Property<long>("payment_to")
                        .HasColumnType("bigint");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("transaction_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("payment_id");

                    b.ToTable("payment");
                });

            modelBuilder.Entity("LE.Account.Entities.Receipt", b =>
                {
                    b.Property<long>("receipt_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric");

                    b.Property<long>("cancelled_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("cancelled_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("cheque_date")
                        .HasColumnType("text");

                    b.Property<string>("cheque_no")
                        .HasColumnType("text");

                    b.Property<string>("customer_name")
                        .HasColumnType("text");

                    b.Property<decimal>("discount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_cancelled")
                        .HasColumnType("boolean");

                    b.Property<string>("nep_entry_date")
                        .HasColumnType("text");

                    b.Property<string>("nep_transaction_date")
                        .HasColumnType("text");

                    b.Property<long>("receipt_from")
                        .HasColumnType("bigint");

                    b.Property<long>("receipt_to")
                        .HasColumnType("bigint");

                    b.Property<string>("remarks")
                        .HasColumnType("text");

                    b.Property<DateTime>("transaction_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("receipt_id");

                    b.ToTable("receipt");
                });

            modelBuilder.Entity("LE.Account.Entities.Transaction", b =>
                {
                    b.Property<long>("transaction_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("nep_entry_date")
                        .HasColumnType("text");

                    b.Property<string>("nep_transaction_date")
                        .HasColumnType("text");

                    b.Property<string>("remarks")
                        .HasColumnType("text");

                    b.Property<DateTime>("transaction_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("voucher_no")
                        .HasColumnType("bigint");

                    b.Property<int>("voucher_type")
                        .HasColumnType("integer");

                    b.HasKey("transaction_id");

                    b.ToTable("transaction");
                });

            modelBuilder.Entity("LE.Account.Entities.TransactionDetail", b =>
                {
                    b.Property<long>("transaction_detail_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("FiscalYearId")
                        .HasColumnType("integer");

                    b.Property<decimal>("balance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("cr_amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("dr_amount")
                        .HasColumnType("numeric");

                    b.Property<long>("ledger_id")
                        .HasColumnType("bigint");

                    b.Property<long>("ref_ledger_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("transaction_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("transaction_id")
                        .HasColumnType("bigint");

                    b.HasKey("transaction_detail_id");

                    b.HasIndex("ledger_id");

                    b.HasIndex("transaction_id");

                    b.ToTable("transaction_detail");
                });

            modelBuilder.Entity("LE.Billing.Entities.BillingSettings", b =>
                {
                    b.Property<long>("settings_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("value")
                        .HasColumnType("bigint");

                    b.HasKey("settings_id");

                    b.HasIndex("key")
                        .IsUnique();

                    b.ToTable("billing_settings");
                });

            modelBuilder.Entity("LE.Billing.Entities.ChiranSales", b =>
                {
                    b.Property<long>("chiran_sales_id")
                        .HasColumnType("bigint");

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric");

                    b.Property<long>("cancelled_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("cancelled_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_cancelled")
                        .HasColumnType("boolean");

                    b.Property<long?>("member_id")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("nep_sales_date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("remarks")
                        .HasColumnType("character varying(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime>("sales_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("sales_type")
                        .HasColumnType("integer");

                    b.Property<decimal>("tax_amount")
                        .HasColumnType("numeric");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("chiran_sales_id");

                    b.ToTable("chiran_sales");
                });

            modelBuilder.Entity("LE.Billing.Entities.ChiranSalesDetail", b =>
                {
                    b.Property<long>("chiran_sales_detail_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("breadth")
                        .HasColumnType("numeric");

                    b.Property<long>("chiran_sales_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("circle_size")
                        .HasColumnType("numeric");

                    b.Property<decimal>("length")
                        .HasColumnType("numeric");

                    b.Property<decimal>("quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("rate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("total_size")
                        .HasColumnType("numeric");

                    b.Property<long>("wood_type_id")
                        .HasColumnType("bigint");

                    b.HasKey("chiran_sales_detail_id");

                    b.HasIndex("chiran_sales_id");

                    b.HasIndex("wood_type_id");

                    b.ToTable("chiran_sales_detail");
                });

            modelBuilder.Entity("LE.Billing.Entities.CounterSales", b =>
                {
                    b.Property<long>("sales_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("bill_amount")
                        .HasColumnType("numeric");

                    b.Property<long>("cancelled_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("cancelled_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("discount_amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_cancelled")
                        .HasColumnType("boolean");

                    b.Property<string>("nep_sales_date")
                        .IsRequired()
                        .HasColumnType("character varying(15)")
                        .HasMaxLength(15);

                    b.Property<decimal>("net_total")
                        .HasColumnType("numeric");

                    b.Property<string>("remarks")
                        .HasColumnType("character varying(120)")
                        .HasMaxLength(120);

                    b.Property<decimal>("return_amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("sales_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("tax_amount")
                        .HasColumnType("numeric");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("sales_id");

                    b.HasIndex("user_id");

                    b.ToTable("counter_sales");
                });

            modelBuilder.Entity("LE.Billing.Entities.CounterSalesDetail", b =>
                {
                    b.Property<long>("sales_detail_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("qty")
                        .HasColumnType("numeric");

                    b.Property<decimal>("rate")
                        .HasColumnType("numeric");

                    b.Property<long>("sales_id")
                        .HasColumnType("bigint");

                    b.Property<long>("service_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("tax_amount")
                        .HasColumnType("numeric");

                    b.HasKey("sales_detail_id");

                    b.HasIndex("sales_id");

                    b.HasIndex("service_id");

                    b.ToTable("counter_sales_details");
                });

            modelBuilder.Entity("LE.Billing.Entities.DayClose", b =>
                {
                    b.Property<long>("day_close_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("eng_close_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("nep_close_date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("day_close_id");

                    b.ToTable("day_close");
                });

            modelBuilder.Entity("LE.Billing.Entities.FirewoodSales", b =>
                {
                    b.Property<long>("firewood_sales_id")
                        .HasColumnType("bigint");

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<long>("cancelled_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("cancelled_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_cancelled")
                        .HasColumnType("boolean");

                    b.Property<string>("nep_sales_date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("others_name")
                        .HasColumnType("text");

                    b.Property<string>("remarks")
                        .HasColumnType("character varying(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime>("sales_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("sales_type")
                        .HasColumnType("integer");

                    b.Property<decimal>("total_amount")
                        .HasColumnType("numeric");

                    b.Property<long?>("type_id")
                        .HasColumnType("bigint");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("firewood_sales_id");

                    b.ToTable("firewood_sales");
                });

            modelBuilder.Entity("LE.Billing.Entities.FirewoodSalesDetail", b =>
                {
                    b.Property<long>("firewood_sales_detail_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric");

                    b.Property<long>("firewood_sales_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("rate")
                        .HasColumnType("numeric");

                    b.Property<long>("stock_item_id")
                        .HasColumnType("bigint");

                    b.HasKey("firewood_sales_detail_id");

                    b.HasIndex("firewood_sales_id");

                    b.HasIndex("stock_item_id");

                    b.ToTable("firewood_sales_detail");
                });

            modelBuilder.Entity("LE.Billing.Entities.Furniture", b =>
                {
                    b.Property<long>("furniture_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("furniture_category_id")
                        .HasColumnType("bigint");

                    b.Property<bool>("is_enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("furniture_id");

                    b.HasIndex("furniture_category_id");

                    b.ToTable("furniture");
                });

            modelBuilder.Entity("LE.Billing.Entities.FurnitureCategory", b =>
                {
                    b.Property<long>("furniture_category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool>("is_enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("furniture_category_id");

                    b.ToTable("furniture_category");
                });

            modelBuilder.Entity("LE.Billing.Entities.FurnitureSales", b =>
                {
                    b.Property<long>("furniture_sales_id")
                        .HasColumnType("bigint");

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<long>("cancelled_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("cancelled_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_cancelled")
                        .HasColumnType("boolean");

                    b.Property<string>("nep_sales_date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("others_name")
                        .HasColumnType("text");

                    b.Property<string>("remarks")
                        .HasColumnType("character varying(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime>("sales_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("sales_type")
                        .HasColumnType("integer");

                    b.Property<decimal>("total_amount")
                        .HasColumnType("numeric");

                    b.Property<long?>("type_id")
                        .HasColumnType("bigint");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("furniture_sales_id");

                    b.ToTable("furniture_sales");
                });

            modelBuilder.Entity("LE.Billing.Entities.FurnitureSalesDetail", b =>
                {
                    b.Property<long>("furniture_sales_detail_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric");

                    b.Property<long>("furniture_id")
                        .HasColumnType("bigint");

                    b.Property<long>("furniture_sales_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("rate")
                        .HasColumnType("numeric");

                    b.HasKey("furniture_sales_detail_id");

                    b.HasIndex("furniture_id");

                    b.HasIndex("furniture_sales_id");

                    b.ToTable("furniture_sales_detail");
                });

            modelBuilder.Entity("LE.Billing.Entities.Member", b =>
                {
                    b.Property<long>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnType("character varying(150)")
                        .HasMaxLength(150);

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("ContactNo")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FamilyRole")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("ImageName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGharmuli")
                        .HasColumnType("boolean");

                    b.Property<string>("MemberCitizenship")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<long>("MembershipId")
                        .HasColumnType("bigint");

                    b.HasKey("MemberId");

                    b.HasIndex("MembershipId");

                    b.ToTable("members");
                });

            modelBuilder.Entity("LE.Billing.Entities.MemberPunishment", b =>
                {
                    b.Property<long>("MemberPunishmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IllegalActivity")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<string>("IsCancelledRemarks")
                        .HasColumnType("text");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("MembershipId")
                        .HasColumnType("bigint");

                    b.Property<string>("NepIssueDate")
                        .HasColumnType("text");

                    b.Property<string>("NepPunishmentValidity")
                        .HasColumnType("text");

                    b.Property<DateTime>("PunishmentValidity")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.HasKey("MemberPunishmentId");

                    b.HasIndex("MembershipId");

                    b.ToTable("member_punishment");
                });

            modelBuilder.Entity("LE.Billing.Entities.Membership", b =>
                {
                    b.Property<long>("MembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Area")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("HasBioGas")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasLPG")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<long>("LedgerId")
                        .HasColumnType("bigint");

                    b.Property<string>("MembershipCode")
                        .IsRequired()
                        .HasColumnType("character varying(25)")
                        .HasMaxLength(25);

                    b.Property<int>("Religion")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("ToleNo")
                        .HasColumnType("text");

                    b.HasKey("MembershipId");

                    b.HasIndex("LedgerId");

                    b.ToTable("membership");
                });

            modelBuilder.Entity("LE.Billing.Entities.MembershipValidity", b =>
                {
                    b.Property<long>("MembershipValidityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("boolean");

                    b.Property<string>("IssueDate")
                        .HasColumnType("text");

                    b.Property<long>("MembershipId")
                        .HasColumnType("bigint");

                    b.Property<string>("NepValidityDate")
                        .HasColumnType("text");

                    b.Property<string>("RenewedDate")
                        .HasColumnType("text");

                    b.Property<DateTime>("ValidityDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("MembershipValidityId");

                    b.HasIndex("MembershipId")
                        .IsUnique();

                    b.ToTable("membership_validity");
                });

            modelBuilder.Entity("LE.Billing.Entities.Service", b =>
                {
                    b.Property<long>("service_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("category_id")
                        .HasColumnType("bigint");

                    b.Property<long>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_enabled")
                        .HasColumnType("boolean");

                    b.Property<long>("ledger_id")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("rate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("tax")
                        .HasColumnType("numeric");

                    b.HasKey("service_id");

                    b.HasIndex("category_id");

                    b.ToTable("services");
                });

            modelBuilder.Entity("LE.Billing.Entities.ServiceCategory", b =>
                {
                    b.Property<long>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("is_enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.HasKey("category_id");

                    b.ToTable("service_categories");
                });

            modelBuilder.Entity("LE.Billing.Entities.Tole", b =>
                {
                    b.Property<long>("tole_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("tole_no")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("tole_id");

                    b.ToTable("tole");
                });

            modelBuilder.Entity("LE.Billing.Entities.WoodBill", b =>
                {
                    b.Property<long>("wood_bill_id")
                        .HasColumnType("bigint");

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("bill_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("cancelled_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("cancelled_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_cancelled")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("nep_bill_date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("remarks")
                        .HasColumnType("character varying(150)")
                        .HasMaxLength(150);

                    b.Property<int>("sales_type")
                        .HasColumnType("integer");

                    b.Property<decimal>("tax_amount")
                        .HasColumnType("numeric");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("wood_bill_id");

                    b.ToTable("wood_bill");
                });

            modelBuilder.Entity("LE.Billing.Entities.WoodBillDetail", b =>
                {
                    b.Property<long>("wood_bill_detail_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("rate")
                        .HasColumnType("numeric");

                    b.Property<long>("wood_bill_id")
                        .HasColumnType("bigint");

                    b.Property<long>("wood_details_id")
                        .HasColumnType("bigint");

                    b.HasKey("wood_bill_detail_id");

                    b.HasIndex("wood_bill_id");

                    b.HasIndex("wood_details_id");

                    b.ToTable("wood_bill_detail");
                });

            modelBuilder.Entity("LE.Billing.Entities.WoodBillMemberTransaction", b =>
                {
                    b.Property<long>("wood_bill_member_transaction_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric");

                    b.Property<bool>("is_cancelled")
                        .HasColumnType("boolean");

                    b.Property<long>("member_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("rate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("tax_amount")
                        .HasColumnType("numeric");

                    b.Property<long>("wood_bill_id")
                        .HasColumnType("bigint");

                    b.Property<long>("wood_details_id")
                        .HasColumnType("bigint");

                    b.HasKey("wood_bill_member_transaction_id");

                    b.HasIndex("member_id");

                    b.HasIndex("wood_bill_id");

                    b.HasIndex("wood_details_id");

                    b.ToTable("wood_bill_members_transaction");
                });

            modelBuilder.Entity("LE.Billing.Entities.WoodBillMembers", b =>
                {
                    b.Property<long>("wood_bill_member_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("member_id")
                        .HasColumnType("bigint");

                    b.Property<long>("wood_bill_id")
                        .HasColumnType("bigint");

                    b.HasKey("wood_bill_member_id");

                    b.HasIndex("member_id");

                    b.HasIndex("wood_bill_id");

                    b.ToTable("wood_bill_members");
                });

            modelBuilder.Entity("LE.Entities.OrganizationSetup.OrganizationSetup", b =>
                {
                    b.Property<long>("organization_setup_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("key")
                        .IsRequired()
                        .HasColumnType("character varying(70)")
                        .HasMaxLength(70);

                    b.Property<string>("value")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.HasKey("organization_setup_id");

                    b.ToTable("organization_setup");
                });

            modelBuilder.Entity("LE.Entities.User.Authentication", b =>
                {
                    b.Property<long>("authentication_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("is_enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.Property<long>("type_id")
                        .HasColumnType("bigint");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("authentication_id");

                    b.ToTable("authentications");
                });

            modelBuilder.Entity("LE.Entities.User.DynamicMenu", b =>
                {
                    b.Property<long>("dynamic_menu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("api_url")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int>("display_order")
                        .HasColumnType("integer");

                    b.Property<string>("icon")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<string>("menu_name")
                        .IsRequired()
                        .HasColumnType("character varying(30)")
                        .HasMaxLength(30);

                    b.Property<long>("module_id")
                        .HasColumnType("bigint");

                    b.Property<long?>("parent_menu_id")
                        .HasColumnType("bigint");

                    b.Property<string>("web_url")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("dynamic_menu_id");

                    b.HasIndex("module_id");

                    b.HasIndex("parent_menu_id");

                    b.ToTable("dynamic_menus");
                });

            modelBuilder.Entity("LE.Entities.User.LoginSession", b =>
                {
                    b.Property<long>("login_session_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("authentication_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("date_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.HasKey("login_session_id");

                    b.HasIndex("authentication_id");

                    b.ToTable("login_sessions");
                });

            modelBuilder.Entity("LE.Entities.User.Module", b =>
                {
                    b.Property<long>("module_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("display_icon")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("module_code")
                        .HasColumnType("character varying(15)")
                        .HasMaxLength(15);

                    b.Property<string>("module_name")
                        .IsRequired()
                        .HasColumnType("character varying(30)")
                        .HasMaxLength(30);

                    b.HasKey("module_id");

                    b.ToTable("modules");
                });

            modelBuilder.Entity("LE.Entities.User.Role", b =>
                {
                    b.Property<long>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("is_enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("role_id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("LE.Entities.User.RolePermissionMap", b =>
                {
                    b.Property<long>("role_permission_map_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("module_id")
                        .HasColumnType("bigint");

                    b.Property<long>("role_id")
                        .HasColumnType("bigint");

                    b.HasKey("role_permission_map_id");

                    b.HasIndex("module_id");

                    b.HasIndex("role_id");

                    b.ToTable("role_permission_maps");
                });

            modelBuilder.Entity("LE.Entities.User.User", b =>
                {
                    b.Property<long>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("address_line_1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("address_line_2")
                        .HasColumnType("text");

                    b.Property<long>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("image_path")
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("primary_contact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("secondary_contact")
                        .HasColumnType("text");

                    b.HasKey("user_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("LE.Entities.User.UserRole", b =>
                {
                    b.Property<long>("user_role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("role_id")
                        .HasColumnType("bigint");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.Property<long>("type_id")
                        .HasColumnType("bigint");

                    b.Property<long?>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("user_role_id");

                    b.HasIndex("role_id");

                    b.HasIndex("user_id");

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("LE.Inventory.Entities.DamagedWoodDetail", b =>
                {
                    b.Property<long>("damaged_wood_details_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("damaged_feet_size")
                        .HasColumnType("numeric");

                    b.Property<decimal>("damaged_fifth_size")
                        .HasColumnType("numeric");

                    b.Property<decimal>("damaged_first_size")
                        .HasColumnType("numeric");

                    b.Property<decimal>("damaged_fourth_size")
                        .HasColumnType("numeric");

                    b.Property<decimal>("damaged_second_size")
                        .HasColumnType("numeric");

                    b.Property<decimal>("damaged_third_size")
                        .HasColumnType("numeric");

                    b.Property<long>("dividor_value")
                        .HasColumnType("bigint");

                    b.Property<decimal>("total_damaged_size")
                        .HasColumnType("numeric");

                    b.Property<long>("wood_details_id")
                        .HasColumnType("bigint");

                    b.HasKey("damaged_wood_details_id");

                    b.HasIndex("wood_details_id");

                    b.ToTable("damaged_wood_detail");
                });

            modelBuilder.Entity("LE.Inventory.Entities.Piling", b =>
                {
                    b.Property<long>("piling_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool>("is_enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("piling_id");

                    b.ToTable("piling");
                });

            modelBuilder.Entity("LE.Inventory.Entities.Purchase", b =>
                {
                    b.Property<long>("purchase_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("nep_purchase_date")
                        .IsRequired()
                        .HasColumnType("character varying(15)")
                        .HasMaxLength(15);

                    b.Property<DateTime>("purchase_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("qty")
                        .HasColumnType("numeric");

                    b.Property<long>("stock_item_id")
                        .HasColumnType("bigint");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("purchase_id");

                    b.HasIndex("stock_item_id");

                    b.ToTable("purchase");
                });

            modelBuilder.Entity("LE.Inventory.Entities.StockCategoryPurpose", b =>
                {
                    b.Property<long>("stock_category_purpose_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("is_enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("stock_category_purpose_id");

                    b.ToTable("purpose_category");
                });

            modelBuilder.Entity("LE.Inventory.Entities.StockItem", b =>
                {
                    b.Property<long>("stock_item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("default_sales_rate")
                        .HasColumnType("numeric");

                    b.Property<bool>("is_enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("character varying(70)")
                        .HasMaxLength(70);

                    b.Property<long?>("stock_item_availability_id")
                        .HasColumnType("bigint");

                    b.Property<long>("stock_unit_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("threshold")
                        .HasColumnType("numeric");

                    b.Property<long>("wood_type_id")
                        .HasColumnType("bigint");

                    b.HasKey("stock_item_id");

                    b.HasIndex("stock_item_availability_id");

                    b.HasIndex("stock_unit_id");

                    b.HasIndex("wood_type_id");

                    b.ToTable("stock_item");
                });

            modelBuilder.Entity("LE.Inventory.Entities.StockItemAvailability", b =>
                {
                    b.Property<long>("stock_item_availability_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("last_updated_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("nep_last_updated_date")
                        .IsRequired()
                        .HasColumnType("character varying(15)")
                        .HasMaxLength(15);

                    b.Property<decimal>("qty")
                        .HasColumnType("numeric");

                    b.Property<long>("stock_item_id")
                        .HasColumnType("bigint");

                    b.HasKey("stock_item_availability_id");

                    b.ToTable("stock_item_availability");
                });

            modelBuilder.Entity("LE.Inventory.Entities.StockMovement", b =>
                {
                    b.Property<long>("stock_movement_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("movement_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("movement_type")
                        .HasColumnType("integer");

                    b.Property<long>("movement_type_id")
                        .HasColumnType("bigint");

                    b.Property<string>("nep_movement_date")
                        .IsRequired()
                        .HasColumnType("character varying(15)")
                        .HasMaxLength(15);

                    b.HasKey("stock_movement_id");

                    b.ToTable("stock_movement");
                });

            modelBuilder.Entity("LE.Inventory.Entities.StockUnit", b =>
                {
                    b.Property<long>("stock_unit_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("is_enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("short_name")
                        .IsRequired()
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.HasKey("stock_unit_id");

                    b.ToTable("stock_unit");
                });

            modelBuilder.Entity("LE.Inventory.Entities.WoodDetails", b =>
                {
                    b.Property<long>("wood_details_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("balla_balli_category_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("circle_size")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("fresh_total_size")
                        .HasColumnType("numeric");

                    b.Property<string>("goliya_number")
                        .IsRequired()
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<int>("grade")
                        .HasColumnType("integer");

                    b.Property<bool>("is_sold")
                        .HasColumnType("boolean");

                    b.Property<decimal>("length")
                        .HasColumnType("numeric");

                    b.Property<long>("piling_id")
                        .HasColumnType("bigint");

                    b.Property<long?>("sales_id")
                        .HasColumnType("bigint");

                    b.Property<long>("stock_category_purpose_id")
                        .HasColumnType("bigint");

                    b.Property<long>("stock_type_id")
                        .HasColumnType("bigint");

                    b.Property<string>("tuna_no")
                        .IsRequired()
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<long>("wood_type_id")
                        .HasColumnType("bigint");

                    b.Property<string>("year")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("wood_details_id");

                    b.HasIndex("piling_id");

                    b.HasIndex("stock_category_purpose_id");

                    b.HasIndex("wood_type_id");

                    b.ToTable("wood_details");
                });

            modelBuilder.Entity("LE.Inventory.Entities.WoodType", b =>
                {
                    b.Property<long>("wood_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("default_sales_rate")
                        .HasColumnType("numeric");

                    b.Property<bool>("is_enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("wood_type_id");

                    b.ToTable("wood_type");
                });

            modelBuilder.Entity("LE.Account.Entities.Ledger", b =>
                {
                    b.HasOne("LE.Account.Entities.LedgerGroup", "ledger_group")
                        .WithMany("ledgers")
                        .HasForeignKey("ledger_group_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LE.Account.Entities.LedgerBalance", b =>
                {
                    b.HasOne("LE.Account.Entities.LedgerGroup", "ledger_group")
                        .WithMany()
                        .HasForeignKey("ledger_group_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LE.Account.Entities.Ledger", "ledger")
                        .WithMany()
                        .HasForeignKey("ledger_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LE.Account.Entities.TransactionDetail", b =>
                {
                    b.HasOne("LE.Account.Entities.Ledger", "ledger")
                        .WithMany("transactionDetail")
                        .HasForeignKey("ledger_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LE.Account.Entities.Transaction", "transaction")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("transaction_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LE.Billing.Entities.ChiranSalesDetail", b =>
                {
                    b.HasOne("LE.Billing.Entities.ChiranSales", "chiranSales")
                        .WithMany("chiran_sales_detail")
                        .HasForeignKey("chiran_sales_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LE.Inventory.Entities.WoodType", "woodType")
                        .WithMany()
                        .HasForeignKey("wood_type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LE.Billing.Entities.CounterSales", b =>
                {
                    b.HasOne("LE.Entities.User.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LE.Billing.Entities.CounterSalesDetail", b =>
                {
                    b.HasOne("LE.Billing.Entities.CounterSales", "sales")
                        .WithMany("counter_sales_details")
                        .HasForeignKey("sales_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LE.Billing.Entities.Service", "service")
                        .WithMany()
                        .HasForeignKey("service_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LE.Billing.Entities.FirewoodSalesDetail", b =>
                {
                    b.HasOne("LE.Billing.Entities.FirewoodSales", "firewoodSales")
                        .WithMany("firewood_sales_detail")
                        .HasForeignKey("firewood_sales_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LE.Inventory.Entities.StockItem", "stockItem")
                        .WithMany()
                        .HasForeignKey("stock_item_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LE.Billing.Entities.Furniture", b =>
                {
                    b.HasOne("LE.Billing.Entities.FurnitureCategory", "furnitureCategory")
                        .WithMany("furnitures")
                        .HasForeignKey("furniture_category_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LE.Billing.Entities.FurnitureSalesDetail", b =>
                {
                    b.HasOne("LE.Billing.Entities.Furniture", "furniture")
                        .WithMany()
                        .HasForeignKey("furniture_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LE.Billing.Entities.FurnitureSales", "furnitureSales")
                        .WithMany("furniture_sales_detail")
                        .HasForeignKey("furniture_sales_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LE.Billing.Entities.Member", b =>
                {
                    b.HasOne("LE.Billing.Entities.Membership", "Membership")
                        .WithMany("MemberDetails")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LE.Billing.Entities.MemberPunishment", b =>
                {
                    b.HasOne("LE.Billing.Entities.Membership", "Membership")
                        .WithMany("MemberPunishments")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LE.Billing.Entities.Membership", b =>
                {
                    b.HasOne("LE.Account.Entities.Ledger", "ledger")
                        .WithMany()
                        .HasForeignKey("LedgerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LE.Billing.Entities.MembershipValidity", b =>
                {
                    b.HasOne("LE.Billing.Entities.Membership", "Membership")
                        .WithOne("MembershipValidity")
                        .HasForeignKey("LE.Billing.Entities.MembershipValidity", "MembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LE.Billing.Entities.Service", b =>
                {
                    b.HasOne("LE.Billing.Entities.ServiceCategory", "service_category")
                        .WithMany("services")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LE.Account.Entities.Ledger", "ledger")
                        .WithMany()
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LE.Billing.Entities.WoodBillDetail", b =>
                {
                    b.HasOne("LE.Billing.Entities.WoodBill", "woodBill")
                        .WithMany("wood_bill_detail")
                        .HasForeignKey("wood_bill_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LE.Inventory.Entities.WoodDetails", "woodDetails")
                        .WithMany()
                        .HasForeignKey("wood_details_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LE.Billing.Entities.WoodBillMemberTransaction", b =>
                {
                    b.HasOne("LE.Billing.Entities.Member", "member")
                        .WithMany()
                        .HasForeignKey("member_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LE.Billing.Entities.WoodBill", "woodBill")
                        .WithMany("WoodBillMemberTransactions")
                        .HasForeignKey("wood_bill_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LE.Inventory.Entities.WoodDetails", "woodDetail")
                        .WithMany()
                        .HasForeignKey("wood_details_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LE.Billing.Entities.WoodBillMembers", b =>
                {
                    b.HasOne("LE.Billing.Entities.Member", "member")
                        .WithMany()
                        .HasForeignKey("member_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LE.Billing.Entities.WoodBill", "woodBill")
                        .WithMany()
                        .HasForeignKey("wood_bill_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LE.Entities.User.DynamicMenu", b =>
                {
                    b.HasOne("LE.Entities.User.Module", "module")
                        .WithMany("menus")
                        .HasForeignKey("module_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LE.Entities.User.DynamicMenu", "parent_menu")
                        .WithMany("sub_menus")
                        .HasForeignKey("parent_menu_id");
                });

            modelBuilder.Entity("LE.Entities.User.LoginSession", b =>
                {
                    b.HasOne("LE.Entities.User.Authentication", "authentication")
                        .WithMany()
                        .HasForeignKey("authentication_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LE.Entities.User.RolePermissionMap", b =>
                {
                    b.HasOne("LE.Entities.User.Module", "module")
                        .WithMany()
                        .HasForeignKey("module_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LE.Entities.User.Role", "role")
                        .WithMany("permissions")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LE.Entities.User.UserRole", b =>
                {
                    b.HasOne("LE.Entities.User.Role", "role")
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LE.Entities.User.User", null)
                        .WithMany("roles")
                        .HasForeignKey("user_id");
                });

            modelBuilder.Entity("LE.Inventory.Entities.DamagedWoodDetail", b =>
                {
                    b.HasOne("LE.Inventory.Entities.WoodDetails", "WoodDetails")
                        .WithMany("DamagedWoodDetails")
                        .HasForeignKey("wood_details_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LE.Inventory.Entities.Purchase", b =>
                {
                    b.HasOne("LE.Inventory.Entities.StockItem", "stock_items")
                        .WithMany("purchases")
                        .HasForeignKey("stock_item_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LE.Inventory.Entities.StockItem", b =>
                {
                    b.HasOne("LE.Inventory.Entities.StockItemAvailability", "stock_item_availability")
                        .WithMany()
                        .HasForeignKey("stock_item_availability_id");

                    b.HasOne("LE.Inventory.Entities.StockUnit", "stock_unit")
                        .WithMany("stockItems")
                        .HasForeignKey("stock_unit_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LE.Inventory.Entities.WoodType", "wood_type")
                        .WithMany()
                        .HasForeignKey("wood_type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LE.Inventory.Entities.WoodDetails", b =>
                {
                    b.HasOne("LE.Inventory.Entities.Piling", "piling")
                        .WithMany("woodDetails")
                        .HasForeignKey("piling_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LE.Inventory.Entities.StockCategoryPurpose", "category_purpose")
                        .WithMany("wood_details")
                        .HasForeignKey("stock_category_purpose_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LE.Inventory.Entities.WoodType", "wood_type")
                        .WithMany("wood_details")
                        .HasForeignKey("wood_type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}

