<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UserSecretsId>04fcf427-2d7d-4ee4-a18a-3933b60614fe</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Areas\Counter\Data\**" />
    <Compile Remove="Areas\Counter\Models\**" />
    <Compile Remove="Areas\Counter\Views\**" />
    <Compile Remove="Areas\Inventory\Data\**" />
    <Compile Remove="ViewModels\**" />
    <Content Remove="Areas\Counter\Data\**" />
    <Content Remove="Areas\Counter\Models\**" />
    <Content Remove="Areas\Counter\Views\**" />
    <Content Remove="Areas\Inventory\Data\**" />
    <Content Remove="ViewModels\**" />
    <EmbeddedResource Remove="Areas\Counter\Data\**" />
    <EmbeddedResource Remove="Areas\Counter\Models\**" />
    <EmbeddedResource Remove="Areas\Counter\Views\**" />
    <EmbeddedResource Remove="Areas\Inventory\Data\**" />
    <EmbeddedResource Remove="ViewModels\**" />
    <None Remove="Areas\Counter\Data\**" />
    <None Remove="Areas\Counter\Models\**" />
    <None Remove="Areas\Counter\Views\**" />
    <None Remove="Areas\Inventory\Data\**" />
    <None Remove="ViewModels\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Autofac" Version="5.1.2" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="6.0.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="6.1.0" />
    <PackageReference Include="LocalizationCultureCore" Version="1.1.2" />
    <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="14.17.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.32" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="3.1.32" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.32" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.1.32" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.32" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="3.1.32" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.1.32" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.32" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.32">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.6" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="2.1.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="3.1.0" />
    <PackageReference Include="Rotativa.AspNetCore" Version="1.1.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="4.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.1.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.35.0" />
    <PackageReference Include="System.Drawing.Common" Version="4.7.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LE.Account.Common\LE.Account.Common.csproj" />
    <ProjectReference Include="..\LE.Account.Factories\LE.Account.Factories.csproj" />
    <ProjectReference Include="..\LE.Billing.Factories\LE.Billing.Factories.csproj" />
    <ProjectReference Include="..\LE.Billing.Service\LE.Billing.Service.csproj" />
    <ProjectReference Include="..\LE.Common\LE.Common.csproj" />
    <ProjectReference Include="..\LE.Inventory.Service\LE.Inventory.Service.csproj" />
    <ProjectReference Include="..\LE.Service\LE.Service.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
    <Folder Include="wwwroot\images\custom\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Views\Shared\Accounting\AccountingReportDecorator.cshtml" />
    <None Include="wwwroot\lib\fontawesome-free\webfonts\fa-brands-400.svg" />
    <None Include="wwwroot\lib\fontawesome-free\webfonts\fa-brands-400.woff2" />
    <None Include="wwwroot\lib\fontawesome-free\webfonts\fa-regular-400.svg" />
    <None Include="wwwroot\lib\fontawesome-free\webfonts\fa-regular-400.woff2" />
    <None Include="wwwroot\lib\fontawesome-free\webfonts\fa-solid-900.svg" />
    <None Include="wwwroot\lib\fontawesome-free\webfonts\fa-solid-900.woff2" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="Areas\Billing\Views\_ViewImports.cshtml">
      <Pack>$(IncludeRazorContentInPack)</Pack>
    </Content>
    <Content Update="Areas\Billing\Views\_ViewStart.cshtml">
      <Pack>$(IncludeRazorContentInPack)</Pack>
    </Content>
    <Content Update="Areas\Inventory\Views\_ViewImports.cshtml">
      <Pack>$(IncludeRazorContentInPack)</Pack>
    </Content>
    <Content Update="Areas\Inventory\Views\_ViewStart.cshtml">
      <Pack>$(IncludeRazorContentInPack)</Pack>
    </Content>
  </ItemGroup>
</Project>