<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Unity.RegistrationByConvention" Version="5.11.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LE.Account.Service\LE.Account.Service.csproj" />
  </ItemGroup>
</Project>
