<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LE.Context\LE.Context.csproj" />
    <ProjectReference Include="..\LE.Inventory.Service\LE.Inventory.Service.csproj" />
  </ItemGroup>

</Project>
