<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LE.Common\LE.Common.csproj" />
    <ProjectReference Include="..\LE.Inventory.Common\LE.Inventory.Common.csproj" />
  </ItemGroup>

</Project>
